[package]
name = "state"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
sha3 = "0.8.0"
hex = "0.3.2"
rlp = "0.3.0"
lru-cache = "0.1.1"
ethereum-types = "0.4"
evm = { path="../evm" }
bytes = "0.4.11"
keccak-hash = "0.1"
cita_trie = { git = "https://github.com/cryptape/cita-trie.git", branch = "master" }

[build-dependencies]

[features]
